[tool.poetry]
name = "superopenai"
version = "0.1.2"
description = "Logging and caching superpowers for the openai sdk"
authors = ["Aman Dhesi <aman@stelolabs.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/villagecomputing/superopenai"
packages = [{ include = "superopenai" }]

[tool.poetry.dependencies]
python = "^3.10"
contextvars = "^2.4"
cachetools = "^5.3.2"
openai = "^1.12.0"
prettytable = "^3.10.0"
tiktoken = "^0.6.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.2"
langchain = "^0.1.11"
langchain-openai = "^0.0.8"
langchain-experimental = "^0.0.53"
langgraph = "^0.0.26"
pandas = "^2.2.1"
matplotlib = "^3.8.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
